from players import Player


amit=Player('amit')
# print(amit.name)
# print(amit.lives)

amit.lives -= 1
print(amit)
amit.lives -= 1
print(amit)
amit.lives -= 1
print(amit)
amit.lives -= 1
print(amit)
# amit.level =2
# print(amit)
# amit.level =+ 7
# print(amit)



# from enemy import Enemy ,Bone_snacher,Blod_drinker

# big_teeth=Enemy('big theth',12,1)
# print(big_teeth)
# big_teeth.take_damage(4)
# print(big_teeth)
# big_teeth.take_damage(8)
# print(big_teeth)
# big_teeth.take_damage(8)
# print(big_teeth)





# ugly_enemy=Bone_snacher('blood drinker')
# print(ugly_enemy)
# ugly_enemy.take_damage(4)
# print(ugly_enemy)
# ugly_enemy.take_damage(4)
# print(ugly_enemy)
# ugly_enemy.take_damage(4)
# print(ugly_enemy)
# ugly_enemy.take_damage(4)
# print(ugly_enemy)
# ugly_enemy.take_damage(7)
# print(ugly_enemy)
# print(ugly_enemy)
# print(ugly_enemy.snatch())

# while ugly_enemy.lives:
#     ugly_enemy.take_damage(1)
#     print(ugly_enemy)

# vampire=Blod_drinker('mother fuker')
# while vampire.lives:
#     # if not vampire.skipped():
#         vampire.take_damage(1)
#         print(vampire)
    
 

# blood_bath=kingBlooddrinker('bloodbath')
# while blood_bath.lives:
#     blood_bath.take_damage(12)
#     print(blood_bath)

    